name: expense_tracker
description: "지출 관리 가계부 앱"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.5+4

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.0.3
  google_fonts: ^6.3.2
  intl: ^0.20.2
  easy_localization: ^3.0.8
  tutorial_coach_mark: ^1.2.11

  # Firebase (iOS용 GoogleService-Info.plist 필요)
  firebase_core: ^4.2.0
  firebase_analytics: ^12.2.0
  firebase_crashlytics: ^5.0.3

  # Local Database
  path_provider: ^2.1.5

  pedantic_mono: ^1.34.0
  http: ^1.5.0

  # Local Database
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  sqlite3_flutter_libs: ^0.5.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1
  drift_dev: ^2.29.0

  # Mockito 추가(Mock)
  mockito: ^5.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#F5F5DC"
  adaptive_icon_foreground: "assets/images/app_icon.png"
